---
title: "Regular Expressions"
author: "Nishad Tupe"
date: "1/28/2019"
output:
html_document:   
---

### RegEx Methods

```{r echo=FALSE, warning=FALSE, message = FALSE}
library(stringr)
library(htmlwidgets)
library(tidyverse)
library(readr)
```

```{r}
x <- c("apple", "banana", "pear")
str_view(x, "an")
```

### import text file
```{r}
text <- read_lines("scraping.txt")
text[1:3]
```

### extract string - test
```{r}
str_extract_all(text, "[0-9]+")[[1]] # list 
```

### build regex
`[a-zA-Z]+\s[0-9][0-9],\s[0-9]{4}`

```{r}
dates <- regex("
[a-zA-Z]+
\\s
[0-9]
[0-9]
,
\\s
[0-9]{4}
", comments = TRUE)
```
### Match regex - print all
```{r}
str_match(text, dates)
```
### Print only dates
```{r}
results = str_match(text, dates)
for (i in results){
  if (!is.na(i)){
    print(i)
  }
}

```

# Another example to replace the date/time format

### Create empty vector to hold the values
```{r}
vector <- character()
for (i in results){
if (!is.na(i)){
vector <- c(vector, i)
print(vector)
}
}
```
### Create replace (Regex) pattern, convert the date in day format.
```{r}
replace2 <- strftime(strptime(vector,"%m %y,%d"),"%A")
```
### use replace function.
```{r}
str_replace(vector,dates,replace2)
```

