---
title: "Week-2 R dataframe basics"
author: "Nishad Tupe"
output: html_document
reference: https://www.datacamp.com/community/tutorials/intro-data-frame-r
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Print out built-in R data frame

```{r}
mtcars
```

## Call head() on mtcars

```{r}
head(mtcars)
```

## Investigate the structure of mtcars 

```{r}
str(mtcars)
```

## Definition of vectors

```{r}
name <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", 
          "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883)
rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)
```

## Create a data frame from the vectors

```{r}
planets_df <- data.frame(name, type, diameter, rotation, rings)
```

## check top rows of the plants_df dataframe

```{r}
head(planets_df)
```

